feat(data): add static data, update workflow templates and config
andreafinlay/ti4-misson-control pull request #5
Opened 2024-01-29 01:47 UTC by andreafinlay

2024-01-29 03:45 UTC, MichaelMansourati reviewed
probably any static data structures should be objects with names for keys for each entity i.e planet name is key for data for that planet

2024-01-29 03:45 UTC, MichaelMansourati commented on src/data/planets.json
> +[
this will probably work better as an object keyed by planet name

2024-01-29 03:46 UTC, MichaelMansourati requested changes
re-orienting review as Change Request

2024-01-30 16:57 UTC, andreafinlay commented
@MichaelMansourati data updated!

2024-02-03 22:13 UTC, merged